### ISSUE TITLE
Add support for Steam

### ISSUE THREAD

**Issue by ahahahaah** [CodyMcCodington/AutoCookieOptout#25]
hello
popups not detected
(clear the cookies 1st in your browser before test)
for example the cookies messages of these sites
https://www.thomann.de/
https://www.chronopost.fr/
https://store.steampowered.com/

same problem with the addon "super agent - automatic cookie consent"

**Comment by CodyMcCodington** [comment]
Hi. Thank you for your report.

Auto Cookie Optout strives to cover a wide range of sites by implementing support for common cookie popup implementations. For example, you may have seen fairly identical looking popups like these on a few sites:

![image](https://user-images.githubusercontent.com/84873117/157104925-c526b6ec-3cb4-48e9-8127-43018c82f785.png)

Because a lot of sites use that same type of popup, we can support those sites fairly easily.

Sites like Thomann's have a custom cookie popup, and unfortunately that's a bit too niche for us to maintain support for. While we do sometimes add support for cookie popups that are unique to one specific site, we only do this for a few huge sites like Google and Amazon. Steam seems big enough to fit that category though. I'll keep this thread open so we can add Steam support in a future release.

**Comment by ahahahaah** [comment]
ok then twitter and facebook could also be added? ^^

**Comment by CodyMcCodington** [comment]
I've tried to implement a Facebook version in the past. Their CSS class names are very unpredictable, and doing text-based comparison would not work outside the American English language. Instagram was a lot more well-behaved, so we do support that one already.

As for Twitter, I haven't found a CSS selector yet that reliably and uniquely targets the "Refuse non-essential cookies" button. The closest I could get was `document.querySelectorAll('.css-901oao.r-1awozwy.r-jwli3a.r-6koalj.r-18u37iz.r-16y2uox.r-37j5jr.r-a023e6.r-b88u0q.r-1777fci.r-rjixqe.r-bcqeeo.r-q4m81j.r-qvutc0')`, which unfortunately also matches the "Accept all cookies" button and 2 unrelated targets. If you happen to find a reliable way to target the right DOM elements for Twitter and Facebook, please let me know 😉

**Comment by ahahahaah** [comment]
thank you
in fact im totally noob at programming languages xD

**Comment by CodyMcCodington** [comment]
Steam support has been added in 0.8.1!
