### ISSUE TITLE
Sites that are not working right now

### ISSUE THREAD

**Issue by sith-on-mars** [CodyMcCodington/AutoCookieOptout#27]
The extension doesn't work on the following sites at the moment. I'll update the lists if I find more:

theguardian.com
abc.net.au
nytimes.com
aok.de

**Comment by sith-on-mars** [comment]
I'm not sure if adding new sites counts as "new feature". You can close it if this is out of your current development plan.

**Comment by CodyMcCodington** [comment]
Hi sith-on-mars,

Sorry for the delay there. Since the sites you mentioned all seem to use site-specific cookie popups, unfortunately covering them would indeed require new features.

What makes ACO feasible to maintain is that many sites use the same cookie popups, allowing the plugin to target many sites with only a few cookie popup clickers. While I have implemented some custom cookie popup clickers for sites like Google and Instagram, every new cookie popup clicker I add increases the maintenance costs of the plugin. Auto Cookie Optout is one of many hobbies I have, so I'm afraid it's not in scope.

That said, thanks for using the plugin, and I hope that it's still useful to you on other sites nonetheless!
