### ISSUE TITLE
Readme does not mention legitimate interests

### ISSUE THREAD

**Issue by sharkwouter** [CodyMcCodington/AutoCookieOptout#28]
**Describe the bug**

I was trying to figure out if this plugin will opt out of legitimate interests as well, but this information is missing from the Readme. Could this be clarified? I personally do not feel like there is a legitimate reason for an advertising company to track me.

**Comment by CodyMcCodington** [comment]
Hi sharkwouter,

Sorry for the wait - I'm only seeing this now.

I understand your desire for clarity. For certain websites, Auto Cookie Optout explicitly goes through [additional steps](https://github.com/CodyMcCodington/AutoCookieOptout/blob/main/src/indirectClickers/quantcast.ts#L18) to also opt out of legitimate interest cookies that sites may keep enabled had the extension simply clicked the "Disagree" option. However, not all cookie popups have toggles for legitimate interest. This may mean that the site you're visiting doesn't try to set cookies on a legitimate interest basis, or that the site doesn't let users opt out of those cookies. Since the extension cannot guarantee that there are no sites on the internet where the second scenario applies, it cannot guarantee that you're always opted out of legitimate interest cookies when it automatically handles the cookie popup.

So the most the extension would be able to do is to opt out of legitimate interest in scenarios where the option is presented. From what I can remember off the top of my head, it does so where possible ([another example](https://github.com/CodyMcCodington/AutoCookieOptout/blob/main/src/directClickers/yahoo.ts#L8)). Further verification would be needed before ACO could guarantee it's being consistent with its legitimate interest optouts, and that's not on the planning. ACO is only one of many hobby projects for me so unfortunately I have to make some compromises.

If the legitimate interest optouts are very important to you, please let me know if you find an alternative that suits your needs. I'd be perfectly happy retiring ACO if a superior alternative is available. Hope this answers your question!
