### ISSUE TITLE
Does Auto Cookie Optout deliberately fail if something unexpected happens?

### ISSUE THREAD

**Issue by bertvandepoel** [CodyMcCodington/AutoCookieOptout#9]
As you probably remember, I asked about several GDPR cookie rejection addons for Firefox on Reddit, and we both had to compete with the ignorant view that just auto-accepting all cookies is fine as long as you then block them again. This noise made it kind of made it difficult to talk about the details of your addon (and the other options). 

I've been wondering whether I should give your addon a try, but I would first like to know more about how it deals with unexpected circumstances. It seems that in general, addons struggle with the constant changes that all these "privacy screens" deliberately make. One of my concerns is that an addon may, in error, accept cookies for me while being confused by a changed privacy screen. I was therefore wondering if your addon contains functionality to notice changes and abort, leaving me to reject cookies myself. Similarly, does your addon check to see what cookies are set after it attempts to reject cookies and can it notify the user (or you) if different cookies are set than expected?

I hope you don't mind the questions, but before deciding on a specific addon, I would like to be as much informed as possible. Especially since I will probably try to help in reporting (or development perhaps) if I find an addon I like.

**Comment by CodyMcCodington** [comment]
I think your use case is valid and desirable. Whether it's feasible, I'm not sure yet.

Currently ACO is, unfortunately, a bit more naive in its setup. If I may oversimplify what it does for a sec, when it detects a familiar cookie popup it usually clicks a series of elements based on CSS selectors. The scripts will often use a function called `clickWhenFound` that waits until a certain CSS selector is present in the page, and then clicks the first element matching it. If the selector never appears, the script stalls but you can still interact with the webpage as if nothing ever happened.

In order for ACO to be able to detect when the popup doesn't look exactly as expected, it'd need a comparison algorithm and a baseline. Packaging screenshots as a baseline would be tricky because websites don't have a fixed width. Storing the inner HTML of a cookie popup as a baseline can be considered. Keeping in mind that cookie screens often consist of multiple popups that may contain asynchronously loaded elements, even that is still a bit of a challenge.

There are some scalability concerns as well. Storing a baseline per website is impossible due to the scale of the internet. I don't have a stable let alone finite list of all websites that this plugin supports, nor do I want to artificially limit the number of supported websites to introduce such comparisons. Having a baseline per cookie popup vendor is also fairly tricky, since websites may configure it to look a certain way, show/hide the "Reject all" button, and customize the button labels. Also keep in mind that these cookie popups may show up in a different language depending on the site and your system settings.

So the best I can think of is to have the scripts time out after X seconds when they don't find a CSS selector they're expecting. But even that can be due to slow internet. Having the extension check the value of certain cookies would be feasible in some cases. Although firstly, your mileage may vary depending on whether the vendor stores easily decodable information about the classes of cookies you've accepted, and secondly, this check can only run after the fact when the consent was already submitted. That limits the appeal.

I like the safety that your suggestion would bring. I too wouldn't want the plugin to accidentally accept all cookies. But my personal time constraints aside, I'd first need to find a way to make anomaly detection technically feasible. For now, I'm inclined to recommend Firefox' tracking protection as well as extensions like Privacy Badger and uBlock Origin as an additional line of defense in case something slips through. It's definitely not ideal but it's at least a bit of a safety net.

**Comment by bertvandepoel** [comment]
I think we're on the same line what the ideal case is. I already have uBlock Origin and tracking protection in place, as well as the Facebook container addon (Privacy Badger I tested years ago and found a bit overbearing, but maybe I should give it another shot). I agree that usually that would be enough even if the addon were to fail. So practically it's probably fine. I do find it difficult to decide whether I just continue to say no manually, or use an addon like yours.

I had also considered some of the technical difficulties. Ideally, one of the country implementations of the GDPR (since that's the quickest option) should include some kind of technical requirement for clear for reject all that makes it automateable across the board. But that's probably not going to happen. 

I guess an option that maybe would sooth some of my worries would be if I ACO could be configured to do nothing, and I could then instruct it to run but not submit. That way I could see it press reject everywhere, go into the legitimate interest submenu to then reject there as well, to then get ready to save/submit (but stop before doing so).

Thing is of course, you're the sole developer of this project, and presumably have a job and hobbies beyond ACO, so I know my request isn't really something feasible. I think we agree however that the main question and concern are valid. I'll think about it some more, I guess :)

**Comment by CodyMcCodington** [comment]
An optional feature to automatically configure the cookie settings correctly but stop short of hitting the save button is theoretically possible. The way I see this working is that ACO only takes action on pages requiring an advanced optout (stopping at submit), while letting you handle the ones with a 'Reject all' button yourself. I may implement a settings screen and refactor the existing clickers at some point to make this behavior possible. For now I'm quite happy serving a single use case, considering the additional time investment and added complexity.

> Ideally, one of the country implementations of the GDPR (since that's the quickest option) should include some kind of technical requirement for clear for reject all that makes it automateable across the board. But that's probably not going to happen.

Actually, I may have some good news on that front. Privacy activist Max Schrems is [taking legal action](https://noyb.eu/en/noyb-files-422-formal-gdpr-complaints-nerve-wrecking-cookie-banners) against websites that intentionally make opting out complicated and seems to be quite successful at it. I'm optimistic that it's a question of time before we get a simple reject button on most websites. As you allude to this would indeed make ACO more robust, since it would hopefully be able to simply click selectors with names like `.rejectAllButton`.

**Comment by bertvandepoel** [comment]
Great to learn about Max Schrems. I didn't know about that yet! Looks like something that could potentially have huge impact. I'll be keeping up-to-date with that now :)

Thanks for considering all my complicated ideas. I'll see in the future what further things happen with the development of ACO. Thank you for all the work you're putting into giving people tools to defend their privacy!

**Comment by CodyMcCodington** [comment]
Thank you for giving me a fresh perspective from someone who has similar privacy values. Even though we have to work within current practical constraints, I think the support of governments and privacy organizations is paving the way towards easier optouts!
